version: "3"
services:
  z52pg:
    image: zabbix/zabbix-server-pgsql:centos-5.2.6
    container_name: z52pg
    ports:
      - "15251:10051"
    environment:
      - TZ=Europe/Riga
      - DB_SERVER_HOST=pg13
      - DB_SERVER_PORT=7413
      - POSTGRES_DB=z52
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - ZBX_STARTPOLLERS=1
      - ZBX_STARTPREPROCESSORS=1
      - ZBX_STARTPROXYPOLLERS=0
      - ZBX_STARTTRAPPERS=2
      - ZBX_STARTDISCOVERERS=0
      - ZBX_CACHEUPDATEFREQUENCY=3600
      - ZBX_STARTHISTORYPOLLERS=1
      - ZBX_STARTALERTERS=1
      - ZBX_STARTJAVAPOLLERS=0
      - ZBX_STARTLLDPROCESSORS=1
      - ZBX_CACHESIZE=256M
      - ZBX_STARTDBSYNCERS=1

# podman-compose up --detach --build
