version: "3"
services:
  z60pg:
    image: zabbix/zabbix-server-pgsql:ol-6.0.30
    container_name: z60pg
    ports:
      - "16051:10051"
    environment:
      - TZ=Europe/Riga
      - DB_SERVER_HOST=pg14
      - DB_SERVER_PORT=7414
      - POSTGRES_DB=z60
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - ZBX_STARTPOLLERS=2
      - ZBX_STARTPREPROCESSORS=1
      - ZBX_STARTTRAPPERS=2
      - ZBX_STARTPROXYPOLLERS=2
      - ZBX_STARTDISCOVERERS=0
      - ZBX_STARTHISTORYPOLLERS=1
      - ZBX_STARTALERTERS=1
      - ZBX_CACHEUPDATEFREQUENCY=6
      - ZBX_STARTJAVAPOLLERS=0
      - ZBX_STARTLLDPROCESSORS=1
      - ZBX_CACHESIZE=256M
      - ZBX_STARTDBSYNCERS=1

# podman-compose up --detach --build
